formats:
  default:
    1:
      texts:
        faction: "Avadia &7"
        player: "%player_name%"
      hoverTexts:
        faction: "Salut"
    2:
      texts:
        faction: "Avadia &7"
        player: "%player_name%"
      hoverTexts:
        faction: "Salut"
  asvadium:
    texts:
      faction: "Avadia &7"
      player: "%player_name%"
    hoverTexts:
      faction: "Salut"
mention:
  text: "%player% vous à mentionné !"
spam:
  text: "Arrete de spam !"
#achat.asvadium